name: Build

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build Docker image
      run: docker build . --file Dockerfile --tag osmo-validator-voting

    - name: Run app then confirm if running
      run: docker run -p 8501:8501 --name app osmo-validator-voting sh -c "streamlit run app.py & sleep 10; pytest tests/end_to_end/test_app.py"
