name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build Docker image
      run: docker build . --file Dockerfile --tag osmo-validator-voting

    - name: Run app
      run: docker run -d -p 8501:8501 --name containerized-app osmo-validator-voting

    - name: Download wait-for script
      run: |
        curl -o wait-for https://raw.githubusercontent.com/vishnubob/wait-f$
        chmod +x wait-for

    - name: Wait for app to start
      run: wait-for localhost:8501 -t 60

    - name: Test if app is running
      run: docker exec -it containerized-app pytest tests/integration/test_app.py

