name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build Docker image
      run: docker build . --file Dockerfile --tag osmo-validator-voting

    - name: Run app
      run: docker run -d -p 8501:8501 --name containerized-app osmo-validator-voting

    - name: Wait for app to start
      run: sleep 60

    - name: Test if app is running
      run: docker exec -it containerized-app pytest tests/integration/test_app.py

