name: Data Refresh

on:
  schedule:
    - cron: '0 */6 * * *' # Runs every 6 hours
  workflow_dispatch:

jobs:

  build_and_run:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build Docker image
      run: docker build . --file Dockerfile --tag osmo-validator-voting
      
    - name: Run ETL job
      env:
        GCS_BUCKET: ${{ secrets.PROD_GCS_BUCKET }}
        GOOGLE_SERVICE_ACCOUNT_JSON: '${{ secrets.PROD_GOOGLE_SERVICE_ACCOUNT_JSON }}'
      run: |
        docker run \
          -e GCS_BUCKET=$GCS_BUCKET \
          -e GOOGLE_SERVICE_ACCOUNT_JSON='$GOOGLE_SERVICE_ACCOUNT_JSON' \
          osmo-validator-voting python -m src.etl.refresh_datasets
