name: End-to-End Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:

  data-refresh-test:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build Docker image
      run: docker build . --file Dockerfile --tag osmo-validator-voting

    - name: Create service account key file
      env:
        GOOGLE_SERVICE_ACCOUNT_JSON: '${{ secrets.PROD_GOOGLE_SERVICE_ACCOUNT_JSON }}'
      run: |
        mkdir credentials 
        printf '%s ' $GOOGLE_SERVICE_ACCOUNT_JSON >| credentials/service_account_key.json;
      
    - name: Test run ETL job
      env:
        GCS_BUCKET: ${{ secrets.TEST_GCS_BUCKET }}
      run: |
        docker run \
          -v $PWD/credentials:/osmosis-validator-voting-comparison/credentials \
          -e GCS_BUCKET=$GCS_BUCKET \
          osmo-validator-voting python -m src.etl.refresh_datasets
