name: Scheduled Data Refresh

on:
  schedule:
    - cron: '0 */6 * * *' # Runs every 6 hours
  workflow_dispatch:

jobs:

  build_and_run:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build Docker image
      run: docker build . --file Dockerfile --tag osmo-validator-voting

    - name: Create service account key file
      env:
        GOOGLE_SERVICE_ACCOUNT_JSON: '${{ secrets.PROD_GOOGLE_SERVICE_ACCOUNT_JSON }}'
      run: |
        mkdir credentials 
        printf '%s ' $GOOGLE_SERVICE_ACCOUNT_JSON >| credentials/service_account_key.json;
 
    - name: Run ETL job
      env:
        GCS_BUCKET: ${{ secrets.PROD_GCS_BUCKET }}
        FLIPSIDE_API_KEY: ${{ secrets.PROD_FLIPSIDE_API_KEY }}
      run: |
        docker run \
          -v $PWD/credentials:/osmosis-validator-voting-comparison/credentials \
          -e GCS_BUCKET=$GCS_BUCKET \
          -e FLIPSIDE_API_KEY=$FLIPSIDE_API_KEY \
          osmo-validator-voting python -m src.etl.refresh_datasets
